//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRON.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUE_Cuentas
    {
        public int CUE_Id { get; set; }
        public string CUE_NickName { get; set; }
        public string CUE_ClavePublica { get; set; }
        public int CUE_Puntos { get; set; }
        public System.DateTime CUE_FechaRegistro { get; set; }
        public System.DateTime CUE_FechaUltimaActualizacion { get; set; }
    }
}
